---
title: "Notas Tarea 5"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## Código que hace una base de datos con las notas


```{r message=FALSE}

library(dplyr)
library(tidyr)

nombres <- c("Rodrigo Gonzalez", "Cecilia Carmona", "Benedicto Romero",
             "Hermman Bauer", "Leontina Quiñones", "Nelson Hermosilla",
             "Felipe Hernandez", "Cristina Dubournais", "Maria Luisa Ubeda", 
             "Amanda Vergara")

pregunta_1 <- c(2,2,2,NA,2,0.5,0.5,0.5,NA,1.5)


pregunta_2 <- c(2,2,2,NA,1.9,1.9,2,1.5,NA,1.9)


pregunta_3 <- c(2,1,1.8,NA,2,2,2,2,NA,2)

tarea_5_df <- data.frame(nombres,pregunta_1,pregunta_2,pregunta_3)

tarea_5_df <- tarea_5_df |>
  mutate(total_puntaje = pregunta_1 + pregunta_2 + pregunta_3) |>
  mutate(nota = total_puntaje + 1) |>
  arrange(nombres)


```

## Tabla de notas

```{r message=FALSE, warning=FALSE}
library(kableExtra)

tarea_5_df |>
  kbl() |>
  kable_styling(bootstrap_options = c("striped", "hover"))
```

## Estadística

```{r message=FALSE, warning=FALSE}
tarea_5_df |>
  summarise(
    promedio = mean(nota, na.rm = T),
    max = max(nota, na.rm = T),
    min = min(nota, na.rm = T)
  ) |>
  pivot_longer(
    cols = everything(),
    names_to = "Estadística",
    values_to = "Valor"
  ) |>
  kbl() |>
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = F)
```